# Generated by Django 5.0.7 on 2024-08-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('event_type', models.CharField(choices=[('DUR', 'Duration'), ('DIS', 'Distance')], max_length=3, verbose_name='Tipo Allenamento')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('elevation_gain', models.FloatField(blank=True, null=True)),
                ('rest_duration', models.DurationField(blank=True, null=True)),
                ('training_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='events.trainingevent')),
            ],
        ),
    ]
